version: '3.3'

services:
  db:
    image: postgres:13-alpine
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=collect
  web:
    build: .
    command: bash -c "flask db migrate && flask db upgrade && flask run -h 0.0.0.0"
    volumes:
      - ./:/project/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db


volumes:
  postgres_data: